[package]
name = "fast-release"
version = "0.0.0-beta.0"
edition = "2021"

[profile.release]
opt-level = 3

[dependencies]
colored = "2.1.0"
git2 = "0.18.1"
log = "0.4.20"
serde = { version = "1.0.193", features = ["derive"] }
serde_yaml = "0.9.29"
